import './globals.css';
import { GeistSans } from 'geist/font/sans';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${GeistSans.className} h-[100dvh] w-[100dvw] bg-zinc-200 text-zinc-950 dark:bg-zinc-900 dark:text-zinc-100`}
      >
        {children}
      </body>
    </html>
  );
}
